global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'minih-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'minih-gateway-service:8080'
          - 'minih-system-service:8081'
          - 'minih-weather-service:8082'
          - 'minih-semantic-registry:8099'
